### ISSUE TITLE
Capsule depends on JDK internal APIs that have been removed from JDK9

### ISSUE THREAD

**Issue by chrisr3** [puniverse/capsule#115] opened 2017-03-14 10:38 UTC
With JDK9 ea+160:

```
   Capsule   -> com.sun.jmx.mbeanserver.JmxMBeanServer  JDK internal API (java.management)
   Capsule   -> sun.management.Agent                    JDK internal API (JDK removed internal API)
   Capsule   -> sun.misc.VMSupport                      JDK internal API (JDK removed internal API)
```

Both of these `sun.` APIs seem to relate to JMX (capsule/src/main/java/Capsule.java):

```
final Properties agentProps = sun.misc.VMSupport.getAgentProperties();
if (agentProps.get(LOCAL_CONNECTOR_ADDRESS_PROP) == null) {
    log(LOG_VERBOSE, "Starting management agent");
    sun.management.Agent.agentmain(null); // starts a JMXConnectorServer that does not prevent the app from shutting down
}
```

**Comment by mikehearn** [comment] 2017-03-14 12:37
I think this is a dupe of #110

**Comment by pron** [comment] 2017-03-15 11:02
Yep. Duplicate.

**Closed as completed by pron** 2017-03-15 11:02 UTC
