### ISSUE TITLE
Closing an application occurred ConcurrentModificationException

### ISSUE THREAD

**Issue by dolphineor** [puniverse/capsule#98] opened 2016-01-23 12:08 UTC
Hi @pron , I currently use capsule to build a executable application jar which embeded web server. When I close application, the exception randomizedly occurred, the message as follow:
```
2016-01-23 19:50:14,384 [Thread-1] INFO  c.github.dolphineor.web.WebAppServer - Undertow web server on port 8081 stopped
CAPSULE EXCEPTION: nullCAPSULE: Exception on thread cleanup: null
CAPSULE EXCEPTION: null while processing null null: null while processing null null: null (for stack trace, run with -Dcapsule.log=verbose)
 (for stack trace, run with -Dcapsule.log=verbose)
Exception in thread "cleanup" java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.next(Unknown Source)
        at Capsule.cleanup0(Capsule.java:1417)
        at Capsule.cleanup(Capsule.java:1403)
        at Capsule.cleanup1(Capsule.java:1390)
        at Capsule.run(Capsule.java:1309)
        at java.lang.Thread.run(Unknown Source)
```
Is there something wrong with me? Thanks in advance.

**Comment by circlespainter** [comment] 2016-01-24 06:14
Can you try with a `1.0.2-SNAPSHOT` build from [this branch](https://github.com/puniverse/capsule/tree/fix-98)?

**Comment by dolphineor** [comment] 2016-01-24 13:25
I tried, but it does not work.

**Comment by circlespainter** [comment] 2016-01-24 13:33
Thanks. The issue seems to be related to a modification of the temporary files list during its recursive deletion. Are you using any caplets? If you could share a reduced project that exhibits the issue it would greatly help, or even just the project build file to start with.

**Comment by dolphineor** [comment] 2016-01-24 13:50
I used [gradle-capsule-plugin](https://github.com/danthegoodman/gradle-capsule-plugin), because of my project built with gradle. This my project's address: [modern-java-web-scaffold](https://github.com/dolphineor/modern-java-web-scaffold). I just built backend project, ran the executable application jar and then closed application. The commands I used as follow:
./gradlew :backend:clean fatCapsule
cd backend/build/libs
java -jar -Xms1g -Xmx1g modern-java-web-scaffold-0.1.0-SNAPSHOT-capsule.jar

**Comment by circlespainter** [comment] 2016-01-26 06:41
I tried several times but I can't seem to reproduce it. How do you stop the server, CTRL-C? Also, which JDK and OS are you using? Does `-Dcapsule.log=debug` logs something more/different around the problem? If you could attach such full log it could help too.

**Comment by dolphineor** [comment] 2016-01-26 06:55
I stopped the server by Ctrl-C, and I have already used debug mode, but it seems like normally. Mostly, it randomizedly occurred. I have a travel these days, when I come back,I'll try my best to find full debug log and notice you in time.

**Comment by circlespainter** [comment] 2016-01-26 06:58
Great, thanks.

**Comment by dolphineor** [comment] 2016-01-29 02:45
I found the trace log, I hope it's helpful for you.
```
CAPSULE: Cleanup
java.lang.Exception: Stack trace2016-01-29 10:40:05,862 [Thread-1] INFO  c.github.dolphineor.web.WebAppServer - Stopping Undertow web server on port 8081

        at Capsule.cleanup1(Capsule.java:1389)
2016-01-29 10:40:05,868 [Thread-1] INFO  io.undertow.servlet - Destroying Spring FrameworkServlet 'modern-java-web-scaffold'
        at Capsule.run(Capsule.java:1309)2016-01-29 10:40:05,870 [Thread-1] INFO  o.s.w.c.s.AnnotationConfigWebApplicationContext - Closing WebApplicationContext for namespace 'modern-java-web-scaffold-servlet': startup date [Fri Jan 29 10:39:48 CST 2016]; parent: Root WebApplicationContext

        at java.lang.Thread.run(Unknown Source)
2016-01-29 10:40:05,886 [Thread-1] INFO  io.undertow.servlet - Closing Spring root WebApplicationContext
CAPSULE: Sending message 1 : 12016-01-29 10:40:05,889 [Thread-1] INFO  o.s.w.c.s.AnnotationConfigWebApplicationContext - Closing Root WebApplicationContext: startup date [Fri Jan 29 10:39:26 CST 2016]; root of context hierarchy

2016-01-29 10:40:05,893 [Thread-1] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-0 - is closing down.
CAPSULE AGENT: Message received 1 : 1
2016-01-29 10:40:05,919 [Thread-1] INFO  c.github.dolphineor.web.WebAppServer - Undertow web server on port 8081 stopped
CAPSULE: Deleting C:\Users\dolphineor\AppData\Local\capsule\apps\com.github.dolphineor.boot.WebAppBoot\.lock
CAPSULE: Cleanup
java.lang.Exception: Stack trace
```

**Comment by circlespainter** [comment] 2016-01-29 07:34
The stack trace you see there is not due to an error, it is just a debugging trace that Capsule prints when it runs debug mode, so the error didn't actually happen in the run that produced the debug log you posted.

A debug log that contains the error should contain the same exception you see in verbose mode, plus more information. Could you try producing a debug log containing the error and attaching it fully?

**Comment by dolphineor** [comment] 2016-01-30 04:11
I used both verbose and debug mode, but did't find ConcurrentModificationException  message. I'm confused about it.

**Comment by circlespainter** [comment] 2016-01-30 11:08
Ok, let's leave the issue open for some time in case you can reproduce it soon. If it doesn't happen again I'll close it but you can always re-open it.

**Comment by dolphineor** [comment] 2016-01-30 14:16
Thanks!

**Comment by circlespainter** [comment] 2016-02-28 05:35
Closing it as almost one month has passed, if you reproduce it just re-open it.

**Closed by circlespainter** 2016-02-28 05:35 UTC
